version: "3"

services:
  postgres:
    container_name: postgr
    image: postgres:13
    command: postgres
    environment:
      POSTGRES_USER: "zvic"
      POSTGRES_PASSWORD: "zvic"
    volumes:
      - ./db/flask_db.sql:/docker-entrypoint-initdb.d/create_tables.sql
    ports:
      - "5433:5432"
  api:
    container_name: flask-api
    build: ./apps
    ports:
      - "5000:5000"
    network_mode: host
    depends_on:
      - postgres
      - cache
  cache:
    container_name: redis-py
    image: redis
    restart: always
    ports:
      - "6379:6379"



    # docker run -p 6379:6379 -d --network=host --name redis-py redis
