--
-- PostgreSQL database dump
CREATE ROLE flask_user PASSWORD 'flask_user' CREATEDB CREATEROLE INHERIT LOGIN;
CREATE DATABASE flask_db WITH OWNER = flask_user ENCODING = 'UTF-8';
\connect flask_db

CREATE TABLE public.goods (
    id integer NOT NULL,
    name character varying(40) NOT NULL,
    price real,
    manufacture_date character varying(11),
    picture_url character varying(100)
);


ALTER TABLE public.goods OWNER TO flask_user;
GRANT ALL ON TABLE public.goods TO flask_user;
GRANT ALL ON SCHEMA public TO flask_user;


--
-- Name: goods_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--
ALTER TABLE public.goods ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.goods_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
--
-- Data for Name: goods; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.goods VALUES (1, 'hepe', 112, '05/07/22', 'pic112');
INSERT INTO public.goods VALUES (2, 'linux', 666, '05/07/22', 'pic112');
INSERT INTO public.goods VALUES (3, 'keyboard666', 666, '05/07/22', 'pic112');
INSERT INTO public.goods VALUES (9, 'apples', 1, '2/2/11', 'ya.com');
INSERT INTO public.goods VALUES (10, 'ananases', 1, '2/2/11', 'fig.com');
INSERT INTO public.goods VALUES (11, 'qiwi', 1000.8, '2/2/11', 'qiwi8.com');



SELECT pg_catalog.setval('public.goods_id_seq', 11, true);


--
-- Name: goods goods_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.goods
    ADD CONSTRAINT goods_pkey PRIMARY KEY (id);

