--
-- PostgreSQL database dump
--

-- Dumped from database version 14.5 (Ubuntu 14.5-0ubuntu0.22.04.1)
-- Dumped by pg_dump version 14.5 (Ubuntu 14.5-0ubuntu0.22.04.1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: goods; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.goods (
    id integer NOT NULL,
    name character varying(40) NOT NULL,
    price real,
    manufacture_date character varying(11),
    picture_url character varying(100)
);


ALTER TABLE public.goods OWNER TO postgres;

--
-- Name: goods_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.goods ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.goods_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: goods; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.goods VALUES (1, 'hepe', 112, '05/07/22', 'pic112');
INSERT INTO public.goods VALUES (2, 'linux', 666, '05/07/22', 'pic112');
INSERT INTO public.goods VALUES (3, 'keyboard666', 666, '05/07/22', 'pic112');
INSERT INTO public.goods VALUES (9, 'apples', 1, '2/2/11', 'ya.com');
INSERT INTO public.goods VALUES (10, 'ananases', 1, '2/2/11', 'fig.com');
INSERT INTO public.goods VALUES (11, 'qiwi', 1000.8, '2/2/11', 'qiwi8.com');


--
-- Name: goods_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.goods_id_seq', 11, true);


--
-- Name: goods goods_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.goods
    ADD CONSTRAINT goods_pkey PRIMARY KEY (id);


--
-- Name: SCHEMA public; Type: ACL; Schema: -; Owner: postgres
--

GRANT ALL ON SCHEMA public TO flask_user;
GRANT ALL ON SCHEMA public TO pg_read_all_data;
GRANT ALL ON SCHEMA public TO pg_write_all_data;
GRANT ALL ON SCHEMA public TO pg_database_owner;


--
-- Name: TABLE goods; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.goods TO flask_user;


--
-- PostgreSQL database dump complete
--

