name: Pull Request for orders
on:
  push:
    branches:
      - orders
jobs:
  pull_request_orders:
    name: PullRequestAction
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
           fetch-depth: 0
      - name: Make PR body
        id: make_pr_body
        run: |
          PR_DESCRIPTION=$(git log origin/master..origin/orders)
          echo "$PR_DESCRIPTION"

      # - name: pull_request_action
      #   uses: vsoch/pull-request-action@master
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #     PULL_REQUEST_BRANCH: "master"
      #     PULL_REQUEST_FROM_BRANCH: "orders"
      #     PULL_REQUEST_BODY: "Test from zvic81 to PR ++ \n just second line"
      #     PULL_REQUEST_TITLE: "testing new PR"
      #     PULL_REQUEST_ASSIGNEES: "zvic81"
      #     PULL_REQUEST_REVIEWERS: "zvic81"
