name: Create Pull Request
on:
  push:
    branches:
      - orders
jobs:

  createPullRequest:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
           fetch-depth: 0

        # if delete this not create PR!!!!! WHY?????????
      - name: Make changes to pull request
        run: date +%s > report.txt

        #  make linting
      - name: Setup python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install depends
        run: pip install autopep8

      - name: Show files
        run: ls ${{ github.workspace }}/app

      - name: Run linters
        id: run_linters
        uses: wearerequired/lint-action@v2
        with:
          autopep8: true
          autopep8_dir: app/


      - name: make variables
        id: make_var
        run: |
          branch=$(git branch --show-current)
          echo branch=$branch >> $GITHUB_OUTPUT
          commits=$(git log --oneline)
          echo 'commits<<EOF' >> $GITHUB_ENV
          echo "$commits" >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV
          # echo "commits=$commits" >> $GITHUB_ENV
          # echo "random-id=$(echo $RANDOM)" >> $GITHUB_OUTPUT
          echo "result of linter ${{ steps.run_linters.outcome }}"

      # - name: create string
      #   run: |
      #     MY_STRING=$(cat << EOF
      #     first line
      #     second line
      #     third line
      #     EOF
      #     )
      #     echo "MY_STRING<<EOF" >> $GITHUB_ENV
      #     echo "$MY_STRING" >> $GITHUB_ENV
      #     echo "EOF" >> $GITHUB_ENV
      #   id: my_string
      # - name: display string
      #   run: |
      #     echo "The string is: ${{ env.commits }}"


      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: Update ${{ steps.make_var.outputs.branch }}
          committer: zvic81 <zvic@list.ru>
          author: ${{ github.actor }} <${{ github.actor }}@zvic81.github.com>
          signoff: false
          branch: orders
          base: master
          title: 'Update ${{ steps.make_var.outputs.branch }}'
          body: |
            Pull request for branch ${{ steps.make_var.outputs.branch }}
            Result of linter Pep8 : ${{ steps.run_linters.outcome }}
            This is all commits in branch:
            - ${{ env.commits }}

            - Auto-generated by [create-pull-request][1]

            [1]: https://github.com/peter-evans/create-pull-request
          labels: |
            report
            automated pr
          assignees: zvic81
          reviewers: zvic81
