name: Create Pull Request
on:
  push:
    branches:
      - orders
jobs:

  createPullRequest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
           fetch-depth: 0

        # if delete this not create PR!!!!! WHY?????????
      - name: Make changes to pull request
        run: date +%s > report.txt

        #  make linting
      - name: Setup python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install depends
        run: pip install autopep8

      - name: Show files
        run: ls ${{ github.workspace }}/app

      - name: Run linters
        id: run_linters
        uses: wearerequired/lint-action@v2
        with:
          autopep8: true
          autopep8_dir: app/


      - name: make variables
        id: make_var
        run: |
          branch=$(git branch --show-current)
          echo branch=$branch >> $GITHUB_OUTPUT
          commits=$(git log --oneline)
          echo commits=$commits >> $GITHUB_OUTPUT
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: Update report
          committer: zvic81 <zvic@list.ru>
          author: ${{ github.actor }} <${{ github.actor }}@zvic81.github.com>
          signoff: false
          branch: orders
          base: master
          title: '[Example] Update report'
          body: |
            Pull request for branch ${{ steps.make_var.outputs.branch }}
            This is all commits in branch
            - ${{ steps.make_var.outputs.commits }}
            - Auto-generated by [create-pull-request][1]
            [1]: https://github.com/peter-evans/create-pull-request
          labels: |
            report
            automated pr
          assignees: zvic81
          reviewers: zvic81
