name : 'test_on_push'
on:
  push:
    branches:
      - orders
jobs:
  test_job:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "🖥️ The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: echo "🍏 This job's status is ${{ job.status }}."
  my_test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      #- name: Docker Compose Action
        # You may pin to the exact commit or the version.
        # uses: isbang/compose-action@9d0371f9eaa290a6b28f9b8d3030f571ecd7da97
        #uses: isbang/compose-action@v1.4.1
        #with:
          # relative path to compose file(s)
          #compose-file: ./docker-compose.yml
          # additional options to pass to `docker-compose` command
          #compose-flags: # optional, default is 
          # additional options to pass to `docker-compose down` command
          #down-flags: # optional, default is 
          # services to perform docker-compose up
          #services: # optional
          # additional options to pass to `docker-compose up` command
          #up-flags: # optional, default is 
